apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sgf-system

resources:
  - namespace.yml
  - postgres-statefulset.yml
  - redis-deployment.yml
  - api-deployment.yml
  - web-admin-deployment.yml
  - ingress.yml

commonLabels:
  app.kubernetes.io/part-of: sgf
  app.kubernetes.io/managed-by: kustomize

images:
  - name: sgf/api
    newTag: latest
  - name: sgf/web-admin
    newTag: latest
