CREATE TABLE adesfa_validations (
    id UUID PRIMARY KEY,
    sale_id UUID NOT NULL REFERENCES sales(id),
    validator_code VARCHAR(40) NOT NULL,
    action_code VARCHAR(20) NOT NULL,
    affiliate_number VARCHAR(80) NOT NULL,
    prescription_number VARCHAR(80) NOT NULL,
    status VARCHAR(20) NOT NULL,
    total_amount NUMERIC(14, 2) NOT NULL,
    patient_amount NUMERIC(14, 2) NOT NULL,
    coverage_amount NUMERIC(14, 2) NOT NULL,
    validated_at TIMESTAMPTZ NOT NULL,
    request_json TEXT NOT NULL,
    response_json TEXT,
    error_message TEXT,
    provider_reference VARCHAR(120),
    integration_mode VARCHAR(20),
    last_http_status INTEGER,
    retryable BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
